#! /bin/bash

set -e
set -x

export ARDUINO_DIRECTORIES_USER="${ARDUINO_DIRECTORIES_USER:-$(pwd)/.arduino/user}"
export HARDWARE_DIR="${HARDWARE_DIR:-${ARDUINO_DIRECTORIES_USER}/hardware/keyboardio}"
export KALEIDOSCOPE_DIR="${KALEIDOSCOPE_DIR:-$(pwd)/.kaleidoscope}"

[ -e ${KALEIDOSCOPE_DIR} ] || git clone --quiet https://github.com/keyboardio/Kaleidoscope.git ${KALEIDOSCOPE_DIR}
(cd ${KALEIDOSCOPE_DIR} && make setup)
git submodule --quiet update --init --recursive
